language: python
python: "3.6"
cache: pip

# only test tagged commits
if: tag IS present

# limit git clone depth
git:
  depth: 3

# required for google chrome
dist: trusty

env:
  global:
    - ES_VERSION=5.6.0
    - JAVA_HOME=/usr/lib/jvm/java-8-oracle/jre
    # S3_ACCESS_KEY
    - secure: "fZ2HsqCfj7BFEWwIaVtr4n86cm8maeFOH8tVpx4ZKMS7O1b7pKYwWKf1HywwpAkXOF00yvpZCBCinJwsYY5VLlHOUA6wHvpv0DN654RmuaxvNUIEn5howh2YB9Z/xCMccLHPr4PsR6lNdQKH0fV5qC56kX701KIqtK0uuTXgT6IVHoS9onJBgggOQnDJ83mn/I0i7wpdshDii46bYyF5Rfg++m5aVAB4WP/LY3/q81J2um2inD2tx2FLG8IjiAZoQOPcdoWhukUSZ1Ngz1pxWuMAIOFZDJ5ysfRNO/OMUKfGs3vJHvSgU84iwUK9EHw43VoDqHSsiGGwvwybjztMO4vOWE7NKDs7mkf9cQerMXf34eKb20EtjTCsIKdjwTpq40ITy/7zPiUlXZEX6ShC1LJHT422N/GqDV4FOBbvJpaLId63ukOqAQ8qVKqKfyGbWRa90DwU9MB2hpYErMBlOliP1GZADekX6A2/3wAO1qmEWIgl7KRNovKy4a6xWNedzEwFHC3ahNAoZn270gXKT+DDv6qrg06kROsBv1dFyeSN7OeWp27M248GHFd8fxPVzdJWQKWUH4oytZ5FNPnc9eHvtF4vrmzku/HYolEgL6Vpo9WQGXYeTkpa93ajzCGAjeZp1bBY3la3PfKB1OlylVWZVhNrLs2tJJBgHPgp1gQ="
    # S3_SECRET_KEY
    - secure: "XNx3VIB2BaaSEhBvXH/mWbxmS/4h5CQBuKKGenzYHgsFYf3XnhVbBnrNkMfd1aamqxS9URprDP8pz0ZhPkbKaXXmXy5QwQYc1UKEUlcozi8HX9BRaW1JFSpGaX6bA6RfEUDcUAqQoKw/HsB95LWo977f+OJGc5EA/K3JMqnGKVfNco7mhNyg4jI5tZfWgMnGCLV5u7/Bo3z51dGcIxg14tIUAiDur8atS5V9KxwgkDAij7vo1QWucGp8Ssrb5VB2Teh4dW9K4Uwg4m02Am7gmVzVHupKax8SSYDhhCiDEfbjPPc2EzJc8KpBK1Lj/xIdAsBkkYXv3QyFvYkG+YUcld97+S4192g9Fgd0RZd9b5v0R3/gNCOaXx6iMdtnM5T7D282GTNvUjAYi74RIU1uYCjrGjgoiRHsOWoUQz6hMOuEj1Ki2gi81bl1lOKN25K3unKyK19eGUNa3oHwx1EK5awx28d5AaxkExDH/0Tf3ZiyzUCvCC5SZ4U8kHCmjhWcDGKPtFUaOSJtYAqcugtm8P4TOQFVHX5Ub+usUmj/P3Ewf6w29ZWnZMhGx64t/jVxkam3SwgRdpw2rLvrjpeUp3VCSn+Ph9b4DiSeYNAlRQa0yEBJysrA82ZRZi4RoixLDr2TyxwwmYseO2A5jxlrCT4J5n7klGMi7QosuJ6OQvM="

  matrix:
    - ONEGOV_APPLICATION=onegov.org
    - ONEGOV_APPLICATION=onegov.election_day
    - ONEGOV_APPLICATION=onegov.town
    - ONEGOV_APPLICATION=onegov.feriennet
    - ONEGOV_APPLICATION=onegov.onboarding
    - ONEGOV_APPLICATION=onegov.gazette
    - ONEGOV_APPLICATION=onegov.intranet

install:
  - pip install boto3
  - python install.py

script:
  - py.test -s

addons:
  postgresql: "9.3"
  apt:
    packages:
      - oracle-java8-set-default
      - google-chrome-stable

stages:
  - install
  - test
  - release

jobs:
  include:
    - stage: install
      install:
        - pip install boto3
        - STAGE='install' python install.py
      script: skip
    - stage: release
      script: skip
      install:
        - pip install boto3
        - STAGE='install' python install.py
        - pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG}/g" > "${TRAVIS_BUILD_DIR}"/requirements.txt
      deploy:
        - provider: releases
          api_key:
            secure: "E88gGnQCqnhx7VT2MNbna+/tMgpQpnV3QWkW29Ae5ne29Hpev3B8VKbW9ICFAWkim811khZQLFvKY8ZWGbRuJqdyud/sNlS25Keh1ThG0StX/TRQOZhLFvIQ6BO4g+cFq888xd7HjouyxNV14woc25ov6G2MZuzQRJYu0AZSX8LzKjSdTGdCy9kykZ+sTZeJAerWfi4jqJASp79G+MSZMtRkNnRdA96c2lDl5sn8vLnyz0R9cZSwLxmwn0lP18jkL+MEreBEtSjir/efDN3po4kYEsBx6lymfdJT31u+B0s4Sqy53STeuFt1zRfu5F2AeZkvBLtfT6U6dGPzZJoCCx1AaWQ/VBL4M7n7OCsY4hGTO7kuM+87WjqoBpDHN+HUpo5zrRvSv5UduM6lsqy5m7w7O5YzDtltKeEdLLbeIe7mOe84Liwat5xnxds7quBION8PCW/JdbUz49FFBuW2MXI0DZ0cvOzyju7SKMnrP7PQ+YS0zKI/WpCKWrdI54+Qomp3hYtUISiUZeZA04uflPhshEOBSZQYzznoSJIJ7t9lnntGVXPpKFqzcl862+U7GzHOa+4qcADDv10+7/6bBlZ2sSE45BTTWLjRw7B0lunBc/g4nALKPvmDbqL6APwBeuGahuKiLVPMlg+WM8e4DILg+LGgGqDcoisH/JlGMrQ="
          file: requirements.txt
          skip_cleanup: true
          on:
            tags: true

        - provider: pypi
          distributions: "sdist bdist_wheel"
          user: seantis
          password:
            secure: "ZUZo17DFF0vmXqbSpwkQoqAVgASINXQV7dQUQpEu0KeQQ8JoWgcmhmWID8+n+Ios3kOOKH/YIMb6PwPT9H2hv7e+ylL04vShBeMCn6wLKkPkfbd9IXiv8nSPfjSQ1Wid2sHpdiBXy6icMZGduidH4dJY2JhVyUQin09YPWILaMI8Gv748h7LqDHLoJ9ZFq/EQIIXuHstDT7y9uBRx6Az9ztWLEgTt1eFv9MdWw0UvAUHSAoBcSFskB4GVO40wZLm0VfEQkmkcNbW19dWVT1MKtFG7wj1dkGsajLZUP1oMfQfjN8XN+1jt4u1d6cil5YAJk6DXE+cBYCdkydRXPF2tjXzHx9viDoA3rSM3WBlhGBrsQDmd1KR90mA/o/X1ozPeFmpWLdXUI5yz0ky/QfTJM/4tEj6DF3ln85WJycMM4Te65YdG5hr8makjxr03lclSkv1W8dC0Z5GtcOYP1JtZVp+0HEOjleYY68/5Zr9t9UjSlfXLRyh7PkBtsyzudzHpgRxBQsRwiUsNPWMCxf1r0wh8rjHHjf2zo+b4wkTkwKEygJmrLxnLZyXIYbHH4QoyMzCD4bb96UWyz0NzKxVuy9XN8M0O0ZZK9JPvssQVU1VNhbt5AaliBCMAT4V9nHHM/FwKNxjHR6Xl+qkY12peMmv6pZ9V2wEBh3Lw74TqSM="
          on:
            tags: true
