language: python
python: "3.4"
cache: pip

env:
    global:
        - ES_URL=https://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-2.2.0.tar.gz
        - ES_BINARY=/tmp/elasticsearch/bin/elasticsearch
    matrix:
        - ONEGOV_APPLICATION=onegov.org
        - ONEGOV_APPLICATION=onegov.town
        - ONEGOV_APPLICATION=onegov.feriennet
        - ONEGOV_APPLICATION=onegov.onboarding
        - ONEGOV_APPLICATION=onegov.election_day

addons:
    postgresql: "9.3"

before_install:
    - npm install --save-dev travis-after-all

install:
    - ./.travis-install.sh

script:
    - py.test -s

after_script:
    - pip freeze | sed -r "s/^-e git.*?egg=([a-z\._]+)$/\1==${TRAVIS_TAG:1}/g" > $TRAVIS_BUILD_DIR/requirements.txt
    - cat requirements.txt
    - |
        $(npm bin)/travis-after-all
        export TRAVIS_AFTER_ALL_EXIT_CODE=$?
        echo $TRAVIS_AFTER_ALL_EXIT_CODE

deploy:

  - provider: releases
    api_key:
        secure: "h2A6AM/O4I8wt6fEdSX4w0PT3+vIZYdJNIIR3zElgSQE5ch4+kusRvKwWJ3v6Ulb2wJe9m7TYKONi/I1Ktin3t/nrEIaHafHQ15QrKXR81u11GBaIC6uQ4lOFg+9s4jksJ3qy76cA5IhiKUuLvgbA/oeUll7qRh+1CBNPCNN/679/DLguH2wH17yxIXGGoVjGrmtS50OmY6PPZWhv+244KcQkN6Co0kfjEiKWngGF/nnLdjwmAPuT3SjnG8qxlbVGPiOST5qpHAs87weqI/CS8TwEtFiCgnRj18uKSFDm6ZijqfrOxxGC/ZztXyfyRbch8MMQJyAGpIaPPOjQcariU6O8wlPp8sBhk3vj14adZo7qN8EI0XkqO9iNMdsrpt7oong3Ucp5dnO9VUxcJZ4jw0zfSCTk9nSl/OyCEiyT19TQDKInTJG2m2uVTTbKY9X3WhAEGWuGuzcmG6muI6eY5g9o1AReIqPoD6jqeuI96898GWOPhiGPF8xcPfbr9vky37C3qwzfgkQb8g0gFtQxKUg/dpwynnEeAYL74PeFuN1H8PRSC7P8rGJaYZjtGapbW8E8UqcOyNe6GFaWHz5yOWmVNDeqxVa3yyLdTIc1wOIHfak2gzFJjC03zy8O74Y7RkNzBViw+BQK8xzN6eYvrEb6HTVB5gxwOLA10gjp+g="
    file: requirements.txt
    skip_cleanup: true
    on:
        tags: true
        condition: $TRAVIS_AFTER_ALL_EXIT_CODE = 0

  - provider: pypi
    distributions: "sdist bdist_wheel"
    user: seantis
    password:
        secure: "ZUZo17DFF0vmXqbSpwkQoqAVgASINXQV7dQUQpEu0KeQQ8JoWgcmhmWID8+n+Ios3kOOKH/YIMb6PwPT9H2hv7e+ylL04vShBeMCn6wLKkPkfbd9IXiv8nSPfjSQ1Wid2sHpdiBXy6icMZGduidH4dJY2JhVyUQin09YPWILaMI8Gv748h7LqDHLoJ9ZFq/EQIIXuHstDT7y9uBRx6Az9ztWLEgTt1eFv9MdWw0UvAUHSAoBcSFskB4GVO40wZLm0VfEQkmkcNbW19dWVT1MKtFG7wj1dkGsajLZUP1oMfQfjN8XN+1jt4u1d6cil5YAJk6DXE+cBYCdkydRXPF2tjXzHx9viDoA3rSM3WBlhGBrsQDmd1KR90mA/o/X1ozPeFmpWLdXUI5yz0ky/QfTJM/4tEj6DF3ln85WJycMM4Te65YdG5hr8makjxr03lclSkv1W8dC0Z5GtcOYP1JtZVp+0HEOjleYY68/5Zr9t9UjSlfXLRyh7PkBtsyzudzHpgRxBQsRwiUsNPWMCxf1r0wh8rjHHjf2zo+b4wkTkwKEygJmrLxnLZyXIYbHH4QoyMzCD4bb96UWyz0NzKxVuy9XN8M0O0ZZK9JPvssQVU1VNhbt5AaliBCMAT4V9nHHM/FwKNxjHR6Xl+qkY12peMmv6pZ9V2wEBh3Lw74TqSM="
    on:
        tags: true
        condition: $TRAVIS_AFTER_ALL_EXIT_CODE = 0
